### ISSUE TITLE
enhancement

### ISSUE THREAD

**Issue by MichaelBosello** [darksmo/jquery-localization-tool#20]
hi, thanks you for this script.
the only problem is that the script doesn't translate the default language.
for example if i write in a label hello and i put
'hello': {
                        'italian' : 'ciao',
                        'French': 'Bonjour',
                         'english': 'hello'
            }
and the default language is french i never see 'bonjour' but i can see 'ciao' and 'hello' again.

**Comment by darksmo** [comment]
Hello, I believe you are not using the plugin correctly. The default language is the language the html page is originally in. If without my plugin the page reads in italian, then the default language is italian. In the list you should specify all the languages but not the default language. Can you make a jsfiddle so that I can check how you are using the plugin?

**Comment by MichaelBosello** [comment]
thanks, https://jsfiddle.net/michaelbosello/fc2ao7s3/

**Comment by darksmo** [comment]
I had to adapt your jsfiddle, which did not work right away for me. It's working as expected at https://jsfiddle.net/fc2ao7s3/1/ . I think the problem occurs because your browser is in Italian. See comments around `lingua =` assignment. The default language is the language of the text in the HTML page rendered by the server, not the browser language!

**Comment by darksmo** [comment]
Perhaps this is what you are looking for https://jsfiddle.net/fc2ao7s3/2/ . In this example `lingua` is the language of the browser. See initial translation triggered via Javascript at line 61.

**Comment by MichaelBosello** [comment]
yes this is what i looking for, thanks you very much. a last problem, with this at load i had the text in italian but the dropdown is set to english, there is a function to set the language selected in dropdown?

**Comment by MichaelBosello** [comment]
Pleease?

**Comment by darksmo** [comment]
Hello,

The initial language is the one the html is originally written in. You could use the "translate" method to trigger the initial translation in the desired language.

Best Regards,
Savio
