### ISSUE TITLE
cannot use classes that are used by multiples elements

### ISSUE THREAD

**Issue by sasarivera** [darksmo/jquery-localization-tool#35]
when I tried to select the text of DOM elements to translate via Class and those have more than one element with the same class I got the error:

Error: A 'class:foam' node was found to contain 2 child nodes. This node must contain exactly one text node!

I think is quite common to have multiple elements with the same class and in my case is a necessity. Is there any way to get around this problem?

Thanks

**Comment by darksmo** [comment]
Hello @sasarivera,

unfortunately this is not supported now - therefore there is an explicit error message for it.

Please try to target a single text node when translating. For example, you cannot translate something like `<span class="foam">this is my <b>bold</b> text</span>`. This is because the text you provide in the translation is interpreted as really just text, and replacing the content of `span.foam` would remove the visual bold stile in the case of the example. The workaround in this case would be to translate separate bits within the span, by separating like: `<span class="foam"><span class="firstBit">this is my</span>&nbsp;<b class="secondBit">bold</b>&nbsp;<span class="thirdBit">text</span></span>`, and then use 'class:firstBit', 'class:secondBit', 'class:thirdBit'.

Best Regards,
Savio
